# Generated by Django 3.1.1 on 2020-09-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default='NONE')),
                ('L1', models.DecimalField(decimal_places=4, max_digits=5)),
                ('Tamb', models.DecimalField(decimal_places=4, max_digits=5)),
                ('Tliq', models.DecimalField(decimal_places=4, max_digits=5)),
                ('Tsuc', models.DecimalField(decimal_places=4, max_digits=5)),
                ('Psuc', models.DecimalField(decimal_places=4, max_digits=5)),
                ('Pliq', models.DecimalField(decimal_places=4, max_digits=5)),
                ('Tsh', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
            options={
                'db_table': 'modelErrors',
            },
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.CharField(max_length=30)),
                ('date_creation', models.DateTimeField(default='NONE')),
                ('date_updated', models.DateTimeField(default='NONE')),
                ('threshold_L1', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('threshold_Tamb', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('threshold_Tliq', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('threshold_Tsuc', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('threshold_Psuc', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('threshold_Pliq', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('threshold_Tsh', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('last_info_plot', models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer')),
                ('last_info_plot_L1', models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer')),
                ('last_info_plot_Tamb', models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer')),
                ('last_info_plot_Tliq', models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer')),
                ('last_info_plot_Tsuc', models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer')),
                ('last_info_plot_Psuc', models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer')),
                ('last_info_plot_Pliq', models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer')),
                ('last_info_plot_Tsh', models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer')),
            ],
            options={
                'db_table': 'modelInfo',
            },
        ),
    ]
