# Generated by Django 3.1.1 on 2020-09-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphGatherer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelinfo',
            name='last_info_plot',
        ),
    ]
