# Generated by Django 3.1.1 on 2020-09-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphGatherer', '0002_remove_modelinfo_last_info_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelinfo',
            name='last_info_plot_L1',
        ),
        migrations.RemoveField(
            model_name='modelinfo',
            name='last_info_plot_Pliq',
        ),
        migrations.RemoveField(
            model_name='modelinfo',
            name='last_info_plot_Psuc',
        ),
        migrations.RemoveField(
            model_name='modelinfo',
            name='last_info_plot_Tamb',
        ),
        migrations.RemoveField(
            model_name='modelinfo',
            name='last_info_plot_Tliq',
        ),
        migrations.RemoveField(
            model_name='modelinfo',
            name='last_info_plot_Tsh',
        ),
        migrations.RemoveField(
            model_name='modelinfo',
            name='last_info_plot_Tsuc',
        ),
    ]
