# Generated by Django 3.1.1 on 2020-09-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphGatherer', '0003_auto_20200913_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinfo',
            name='last_info_plot_L1',
            field=models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer'),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='last_info_plot_Pliq',
            field=models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer'),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='last_info_plot_Psuc',
            field=models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer'),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='last_info_plot_Tamb',
            field=models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer'),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='last_info_plot_Tliq',
            field=models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer'),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='last_info_plot_Tsh',
            field=models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer'),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='last_info_plot_Tsuc',
            field=models.FileField(default='static/graphGatherer/diel.png', upload_to='static/graphGatherer'),
        ),
    ]
